// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using everis.SimpleProject.Data.EF;

namespace everis.SimpleProject.Data.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181228114030_AjusteMigrationsThomas")]
    partial class AjusteMigrationsThomas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime?>("DataInativacao");

                    b.Property<string>("Descricao");

                    b.Property<int>("IdProjeto");

                    b.Property<string>("Path");

                    b.Property<int?>("ProjetoId");

                    b.Property<int>("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.Change", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataHoraCadastro");

                    b.Property<DateTime?>("DataInativacao");

                    b.Property<string>("Descricao");

                    b.Property<short>("HorasImpacto");

                    b.Property<int>("IdProjeto");

                    b.Property<int?>("ProjetoId");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Changes");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime?>("DataInativacao");

                    b.Property<bool>("Disponivel");

                    b.Property<string>("EmailCorporativo");

                    b.Property<int>("Funcao");

                    b.Property<int>("Funcional");

                    b.Property<int>("IdPessoa");

                    b.Property<string>("NomeMaquina");

                    b.Property<int>("Perfil");

                    b.Property<int?>("PessoaId");

                    b.Property<string>("Racf");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Colaboradors");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime?>("DataInativacao");

                    b.Property<string>("Nome");

                    b.Property<int>("Segmento");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.EsforcoProjeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime?>("DataFim");

                    b.Property<DateTime?>("DataInativacao");

                    b.Property<DateTime?>("DataInicio");

                    b.Property<DateTime>("DataRegistro");

                    b.Property<int>("IdProjetoPessoa");

                    b.Property<int?>("ProjetoPessoaId");

                    b.Property<short>("QtdHorasDia");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoPessoaId");

                    b.ToTable("EsforcoProjetos");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<long>("CPF");

                    b.Property<DateTime?>("DataInativacao");

                    b.Property<string>("Documento");

                    b.Property<string>("Email");

                    b.Property<int?>("EmpresaId");

                    b.Property<string>("FotoPath");

                    b.Property<int>("IdEmpresa");

                    b.Property<string>("Nome");

                    b.Property<int>("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<string>("BeneficioEntregue");

                    b.Property<string>("BeneficioResidual");

                    b.Property<string>("CentroCusto");

                    b.Property<DateTime>("DataEntrega");

                    b.Property<DateTime?>("DataInativacao");

                    b.Property<DateTime>("DataInicio");

                    b.Property<DateTime>("DataPrevista");

                    b.Property<int?>("EmpresaId");

                    b.Property<string>("EscopoProjeto");

                    b.Property<string>("ForaEscopoProjeto");

                    b.Property<int>("IdEmpresa");

                    b.Property<string>("LicoesAprendidas");

                    b.Property<string>("Nome");

                    b.Property<string>("Premissas");

                    b.Property<string>("ProblemasExecucao");

                    b.Property<int>("QtdHorasServico1");

                    b.Property<int>("QtdHorasServico2");

                    b.Property<int>("QtdHorasServico3");

                    b.Property<string>("Riscos");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.ProjetoPessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime?>("DataInativacao");

                    b.Property<int>("PessoaId");

                    b.Property<int>("ProjetoId");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("ProjetoPessoas");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.ProjetoPessoaAtribuicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<int>("Atribuicao");

                    b.Property<DateTime?>("DataInativacao");

                    b.Property<int>("IdProjetoPessoa");

                    b.Property<int?>("ProjetoPessoaId");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoPessoaId");

                    b.ToTable("ProjetoPessoaAtribuicoes");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime?>("DataInativacao");

                    b.Property<int>("IdPessoa");

                    b.Property<string>("NumeroTelefone");

                    b.Property<int?>("PessoaId");

                    b.Property<int>("TipoTelefone");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime>("DataCadastro");

                    b.Property<DateTime?>("DataInativacao");

                    b.Property<string>("Email");

                    b.Property<string>("NomeUsuario");

                    b.Property<string>("Senha");

                    b.Property<bool>("SenhaTemporaria");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.Anexo", b =>
                {
                    b.HasOne("everis.SimpleProject.Domain.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.Change", b =>
                {
                    b.HasOne("everis.SimpleProject.Domain.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.Colaborador", b =>
                {
                    b.HasOne("everis.SimpleProject.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.EsforcoProjeto", b =>
                {
                    b.HasOne("everis.SimpleProject.Domain.Models.ProjetoPessoa", "ProjetoPessoa")
                        .WithMany()
                        .HasForeignKey("ProjetoPessoaId");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.Pessoa", b =>
                {
                    b.HasOne("everis.SimpleProject.Domain.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.Projeto", b =>
                {
                    b.HasOne("everis.SimpleProject.Domain.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.ProjetoPessoa", b =>
                {
                    b.HasOne("everis.SimpleProject.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("everis.SimpleProject.Domain.Models.Projeto", "Projeto")
                        .WithMany("ProjetosPessoas")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.ProjetoPessoaAtribuicao", b =>
                {
                    b.HasOne("everis.SimpleProject.Domain.Models.ProjetoPessoa", "ProjetoPessoa")
                        .WithMany()
                        .HasForeignKey("ProjetoPessoaId");
                });

            modelBuilder.Entity("everis.SimpleProject.Domain.Models.Telefone", b =>
                {
                    b.HasOne("everis.SimpleProject.Domain.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId");
                });
#pragma warning restore 612, 618
        }
    }
}
